### ISSUE TITLE
_new_from_pretrained does not patch from_pretrained correctly with Transformers v4.50

### ISSUE THREAD

**Issue by dragoneye-alex** [NVIDIA/TensorRT-Model-Optimizer#169]
## Describe the bug
The patch doesn't work now because the function signature for from_pretrained changed in Transformers v4.50 with https://github.com/huggingface/transformers/pull/36033

### Steps/Code to reproduce bug
Import modelopt.torch.opt.plugins.huggingface, and then try to load a pretrained model from transformer. 

We get the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/pytorch/lib/python3.11/site-packages/modelopt/torch/opt/plugins/huggingface.py", line 84, in _new_from_pretrained
    model = types.MethodType(cls._modelopt_cache["from_pretrained"].__func__, cls)(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/pytorch/lib/python3.11/site-packages/transformers/modeling_utils.py", line 272, in _wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/pytorch/lib/python3.11/site-packages/transformers/modeling_utils.py", line 4455, in from_pretrained
    ) = cls._load_pretrained_model(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: _new__load_pretrained_model() missing 1 required positional argument: 'pretrained_model_name_or_path'
```

### Expected behavior
It should work.

**Comment by ishan-modi** [comment]
It should be available in next release - https://github.com/NVIDIA/TensorRT-Model-Optimizer/pull/165

**Comment by kevalmorabia97** [comment]
`nvidia-modelopt==0.27.0` is released now which works with transformers 4.50 as well
