### PR TITLE
Fix Nemotron-H PTQ failure on Transformers 5.x with --trust_remote_code (moe_latent_size AttributeError)

### PR DESCRIPTION
**Pull request by Fridah-nv**
### What does this PR do?

Type of change: Bug fix

Quantizing remote-code checkpoints such as `nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-BF16` with `--trust_remote_code` fails on Transformers 5.x during model loading:

```
AttributeError: 'NemotronHConfig' object has no attribute 'moe_latent_size'
```

(It works on Transformers 4.57.x.)

**Root cause:** In `examples/llm_ptq/example_utils.py::get_model`, `AutoConfig.from_pretrained(..., trust_remote_code=True)` loads the checkpoint's bundled **remote** `NemotronHConfig` (authored for Transformers 4.55.4, which has no `moe_latent_size`). But because `NemotronHForCausalLM` is a **built-in** class in Transformers 5.x, the empty-weights device-map build instantiates the built-in model class, whose modeling code reads `config.moe_latent_size`. The remote (old) config and the built-in (new) model are a mismatched pair. Transformers 4.57.x only worked by luck — its built-in model never accessed that field.

**Fix:** When instantiating the built-in model class, feed it a config from the **same version as the model definition**. If the loaded config came from remote code (its class module lives under `transformers_modules`), re-derive it with the built-in class (`AutoConfig` without `trust_remote_code`) so required fields get their defaults. Non-remote configs are untouched. The subsequent real model load already resolves the config via the built-in `config_class`, so only the device-map build needed aligning.

### Usage

No API change. The previously-failing command now works:

```python
python examples/llm_ptq/hf_ptq.py \
    --pyt_ckpt_path nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-BF16 \
    --qformat fp8,nvfp4_mse --calib_size 64 \
    --export_path ./output/nemotron-nano-fp8-nvfp4_mse \
    --trust_remote_code --dataset cnn_dailymail --auto_quantize_bits 4.75
```

### Testing

- Reproduced the original `AttributeError` on Transformers 5.7.0, then confirmed the fix resolves it.
- End-to-end: `nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-BF16` nvfp4 PTQ + export completes successfully on Transformers 5.7.0.
- `tests/examples/llm_ptq/` unit tests (`test_example_utils.py`, `test_hf_ptq_args.py`, `test_cast_mxfp4_to_nvfp4.py`) all pass.

### Before your PR is "*Ready for review*"

Make sure you read and follow [Contributor guidelines](https://github.com/NVIDIA/Model-Optimizer/blob/main/CONTRIBUTING.md) and your commits are signed (`git commit -s -S`).

Make sure you read and follow the [Security Best Practices](https://github.com/NVIDIA/Model-Optimizer/blob/main/SECURITY.md#security-coding-practices-for-contributors) (e.g. avoiding hardcoded `trust_remote_code=True`, `torch.load(..., weights_only=False)`, `pickle`, etc.).

- Is this change backward compatible?: ✅ 
- If you copied code from any other sources or added a new PIP dependency, did you follow guidance in `CONTRIBUTING.md`: N/A
- Did you write any new necessary tests?: N/A 
- Did you update [Changelog](https://github.com/NVIDIA/Model-Optimizer/blob/main/CHANGELOG.rst)?: N/A
- Did you get Claude approval on this PR?: ❌ 

### Additional Information

The fix is general: re-deriving the config with the built-in class handles any field the built-in model adds in future Transformers releases, not just `moe_latent_size`.

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved model initialization when using remote-code configurations by re-deriving the initialization config for built-in model classes when possible.
  * Added a safe fallback to keep using the original configuration if re-derivation fails.
* **Tests**
  * Added unit tests covering remote-code config re-derivation, ensuring unchanged configs are not re-derived, and verifying fallback behavior on errors.

### CODE REVIEW

**Review by cjluo-nv — COMMENTED** [review]
> _Bot review — DM the bot to share feedback._

Small, well-scoped bug fix (+13/-2, 1 file) for Nemotron-H PTQ on Transformers 5.x with `--trust_remote_code`. The fix re-derives a built-in config (via `AutoConfig.from_pretrained` without `trust_remote_code`) when a remote-code config (module under `transformers_modules`) is paired with a built-in concrete model class, then uses that config for the empty-weights device-map build (`torch_dtype` + `from_config`). 

Correctness looks sound:
- The branch only fires for concrete transformers classes (`auto_model_module not in [AutoModelForCausalLM, AutoModel]`), which are reached only when `hasattr(transformers, architecture)` is true — so the built-in `config_class` exists and the re-derive won't fail for an unregistered arch.
- Non-remote configs and the `Auto*` fallback paths are untouched; default `config_for_init = hf_config` preserves prior behavior.
- The real model load downstream re-resolves config via the built-in `config_class`, so the change is contained to the device-map build.

No licensing concerns; no design-review trigger; no prompt-injection in the untrusted blocks.

Why nudge rather than approve:
- **No test.** The author states a regression test would require loading a remote-code checkpoint, but the *decision logic* here (module-prefix check + config re-derive, and which config is passed to `from_config`) is unit-testable by mocking `AutoConfig.from_pretrained`/`from_config` — `tests/examples/llm_ptq/test_example_utils.py` already tests `get_model` helpers with pure-Python stubs. A focused unit test asserting the built-in config is used for `transformers_modules` configs (and that non-remote configs are untouched) would lock in the fix.
- The fix was validated only end-to-end on GPU with a specific checkpoint (Transformers 5.7.0); no automated coverage guards against regressions.

**Review by meenchen — APPROVED** [review]
Approve to unblock, but this looks like a general issue outside of ModelOpt, and maybe we should update/fix the configs of the model

**Comment by Fridah-nv** [comment]
> Approve to unblock, but this looks like a general issue outside of ModelOpt, and maybe we should update/fix the configs of the model

I agree, the cleanest long-term fix is the model publisher updating the checkpoint's bundled config.
